source_name: "Driving Perception Cameras (Hard/Complex)"
source_type: "video"
source_mode: "http_video"
source_list:
  - name: "driving_perception_hard_complex_camera"
    url: ""
    dir: "driving_perception_hard_complex/"
    metadata:
      resolution: "1080p"
      fps: 30
      encoding: "h264"
      buffer_size: 4
